- hosts: all

  roles:
    - common
    - dev
    - com
    - office
    - razer
    - multimedia
    - android
    - embedded

  tasks:
    - name: Install packages
      pacman: name={{ item }}
      with_items:
        - vim
        - xlockmore
        - tmux
        - tlp
        - tlp-rdw
        - git
        - wget
        - curl
        - tree
      become: yes

    - name: Check RTC in local time zone
      shell: "timedatectl | grep -q 'RTC in local TZ: yes'"
      register: rtc_in_local_time_zone
      ignore_errors: True

    - name: Linux/windows time issue
      command: timedatectl set-local-rtc 1 --adjust-system-clock
      when: not rtc_in_local_time_zone
      become: yes

