- name: Install snap
  aur: name=snapd user=robin
  become: yes

- name: Enable snapd service
  systemd:
    name: snapd.socket
    enabled: yes
    state: started
    user: no
  become: yes

- name: Viewers
  pacman: name={{ item }}
  with_items:
    - evince
  become: yes

