- name: Install docker
  pacman: name={{ item }}
  with_items:
    - docker
    - docker-compose
    - docker-machine
  become: yes

- name: Ensure docker service is running
  service: name=docker state=started enabled=yes
  become: yes

- name: Install Visual Studio code
  aur: name=visual-studio-code-bin user=robin
  become: yes

- name: Install debugger tools
  pacman: name={{ item }}
  with_items:
    - gdb
    - gdb-common
    - valgrind
    - strace
  become: yes

- name: Serial tools
  pacman: name={{ item }}
  with_items:
    - ckermit
    - screen
  become: yes

- name: Extra tools
  pacman: name={{ item }}
  with_items:
    - tig
    - hexedit
  become: yes

- name: Install extra languages
  pacman: name={{ item }}
  with_items:
    - go
    - nodejs
    - npm
    - rust
    - jdk8-openjdk
  become: yes

- name: Python extra
  pacman: name={{ item }}
  with_items:
    - python-virtualenv
    - python2-virtualenv
  become: yes

- name: QT5
  pacman: name={{ item }}
  with_items:
    - qt5-base
    - qt5-tools
    - qt5-declarative
    - python-pyqt5
    - qtcreator
  become: yes

- name: QT5 extra
  pacman: name={{ item }}
  with_items:
    - qt5-charts
    - qt5-connectivity
    - qt5-networkauth
    - qt5-serialport
    - qt5-websockets
  become: yes

- name: Virtualization
  pacman: name={{ item }}
  with_items:
    - virt-manager
    - virt-viewer
    - virt-install
    - libvirt-python
  become: yes

